; Configuración de límites de subida de archivos para este proyecto
; Este archivo puede no funcionar en todos los servidores
; Si no funciona, modifica el php.ini principal de XAMPP

upload_max_filesize = 40M
post_max_size = 45M
max_execution_time = 300
max_input_time = 300
memory_limit = 512M
max_file_uploads = 20

